# docker build -f Dockerfile_main -t ai-training-cnn:v1 .
# main Dockerfile for the AI training CNN application
# 1. 基础镜像（依赖变了才需要重新 build）
#docker build -f Dockerfile.base -t ai-training-cnn-base:v1 .
# 2. 业务镜像（代码改了就 build 这个）
#docker build -f Dockerfile_main -t ai-training-cnn:v1 .

FROM ai-training-cnn-base:v1
WORKDIR /app
COPY . .
COPY fx-bot.cron /etc/cron.d/fx-bot
RUN chmod 0644 /etc/cron.d/fx-bot
RUN mkdir -p /app/logs /app/state

CMD ["cron", "-f"]