# fx_trade_config.py
# Strategy, risk, execution, pivot & MC parameters
from config import (
    MODE, MIN_PROB, STRENGTH_GAP_THRESHOLD,
    MAX_TOTAL_TRADES, MAX_PER_USD_GROUP, MAX_PER_JPY_GROUP,
    DEFAULT_LOT_SIZE, ENABLE_PIVOTS, PIVOT_BIAS_CHECK, PIVOT_METHOD,
    DEFAULT_PAIRS, YAHOO_TO_OANDA, TIMEFRAME,
    ALLOW_TOP_N, ALLOW_BOTTOM_N, DEBUG_EDGE_REASON, NO_SIDE_WAYS_TRADE,
    VOL_LOW_THRESHOLD, VOL_HIGH_THRESHOLD,
    RANGE_LOW_PCT, RANGE_HIGH_PCT,
    TP_MULT_SIDEWAYS, TP_MULT_NORMAL, TP_MULT_STRONG,
    MIN_TREND_STRENGTH, MIN_REWARD_RISK, REENTRY_COOLDOWN_MINUTES
)

class TradeConfig:
    # ——— MODE & STRENGTH ———
    MODE = MODE if "MODE" in dir() else "LEVEL10"
    MIN_PROB = MIN_PROB if "MIN_PROB" in dir() else 0.45
    STRENGTH_GAP_THRESHOLD = STRENGTH_GAP_THRESHOLD if "STRENGTH_GAP_THRESHOLD" in dir() else 7
    ALLOW_TOP_N = ALLOW_TOP_N if "ALLOW_TOP_N" in dir() else 3
    ALLOW_BOTTOM_N = ALLOW_BOTTOM_N if "ALLOW_BOTTOM_N" in dir() else 3
    NO_SIDE_WAYS_TRADE = NO_SIDE_WAYS_TRADE if "NO_SIDE_WAYS_TRADE" in dir() else True
    MIN_TREND_STRENGTH = MIN_TREND_STRENGTH if "MIN_TREND_STRENGTH" in dir() else 0.05

    # ——— PIVOTS ———
    ENABLE_PIVOTS = ENABLE_PIVOTS if "ENABLE_PIVOTS" in dir() else False
    PIVOT_BIAS_CHECK = PIVOT_BIAS_CHECK if "PIVOT_BIAS_CHECK" in dir() else True
    PIVOT_METHOD = PIVOT_METHOD if "PIVOT_METHOD" in dir() else "Classic"

    # ——— RISK & EXECUTION ———
    MAX_TOTAL_TRADES = MAX_TOTAL_TRADES if "MAX_TOTAL_TRADES" in dir() else 3
    MAX_PER_USD_GROUP = MAX_PER_USD_GROUP if "MAX_PER_USD_GROUP" in dir() else 3
    MAX_PER_JPY_GROUP = MAX_PER_JPY_GROUP if "MAX_PER_JPY_GROUP" in dir() else 3
    DEFAULT_LOT_SIZE = DEFAULT_LOT_SIZE if "DEFAULT_LOT_SIZE" in dir() else 10000
    MIN_REWARD_RISK = MIN_REWARD_RISK if "MIN_REWARD_RISK" in dir() else 1.0
    REENTRY_COOLDOWN_MINUTES = REENTRY_COOLDOWN_MINUTES if "REENTRY_COOLDOWN_MINUTES" in dir() else 60

    # ——— TP / VOLATILITY ———
    VOL_LOW_THRESHOLD = VOL_LOW_THRESHOLD if "VOL_LOW_THRESHOLD" in dir() else 4.0
    VOL_HIGH_THRESHOLD = VOL_HIGH_THRESHOLD if "VOL_HIGH_THRESHOLD" in dir() else 7.0
    RANGE_LOW_PCT = RANGE_LOW_PCT if "RANGE_LOW_PCT" in dir() else 0.20
    RANGE_HIGH_PCT = RANGE_HIGH_PCT if "RANGE_HIGH_PCT" in dir() else 0.50
    TP_MULT_SIDEWAYS = TP_MULT_SIDEWAYS if "TP_MULT_SIDEWAYS" in dir() else 1.5
    TP_MULT_NORMAL = TP_MULT_NORMAL if "TP_MULT_NORMAL" in dir() else 2.0
    TP_MULT_STRONG = TP_MULT_STRONG if "TP_MULT_STRONG" in dir() else 2.5

    # ——— INSTRUMENTS & TIMEFRAME ———
    DEFAULT_PAIRS = DEFAULT_PAIRS if "DEFAULT_PAIRS" in dir() else []
    YAHOO_TO_OANDA = YAHOO_TO_OANDA if "YAHOO_TO_OANDA" in dir() else {}
    TIMEFRAME = TIMEFRAME if "TIMEFRAME" in dir() else "15m"
    GRANULARITY_MAP = {"15m": "M15", "1h": "H1", "4h": "H4", "D": "D"}
    OANDA_GRAN = GRANULARITY_MAP.get(TIMEFRAME, "H1")

    # ——— DEBUG ———
    DEBUG_EDGE_REASON = DEBUG_EDGE_REASON if "DEBUG_EDGE_REASON" in dir() else True

trade_config = TradeConfig()